"""initial

Revision ID: 9adac19ef804
Revises: 
Create Date: 2024-04-16 00:17:39.801218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adac19ef804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_pct', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date', name='_name_time_uc')
    )
    op.create_index(op.f('ix_stocks_country'), 'stocks', ['country'], unique=False)
    op.create_index(op.f('ix_stocks_currency'), 'stocks', ['currency'], unique=False)
    op.create_index(op.f('ix_stocks_date'), 'stocks', ['date'], unique=False)
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_date'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_currency'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_country'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
